mock ports:
  - /dev/ttyUSB0
  - /dev/ttyUSB1

baudrate: 57600

data folder: "data/"

ScoutScale logo: "_resources/ss_logo.jpg"

team logo: "_resources/team icon.png"

calibrate data points: 2

default units: "lb"

units:
  - lb
  - kg
