Firebase:
  key: _config/key.json
  collection name: Scale App
  labels:
    weight: Weight
    units: Unit
    date: Date
    zone: Zone
  uploading data: False

Local Data Collection:
  folder: data/
  labels:
    weight: Weight
    units: Unit
    date: Capture Date
    zone: Zone
  default file name: ScoutScale_data.csv
  new file creation mode: False
  
Serial:
  baudrate: 57600
  mock ports:
  - /dev/ttyUSB0
  - /dev/ttyUSB1

weight units:
  default unit: lb
  compatible units:
  - lb
  - kg

calibrate data points: 2

web app URL: https://scout-scale-1.web.app



